<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="camera_length" value="0.01"/>
  <xacro:property name="camera_width" value="0.1"/>
  <xacro:property name="camera_height" value="0.05"/>

  <xacro:property name="camera_mass" value="0.1"/>
  <xacro:property name="Ixx" value="${1.0/12.0 * camera_mass * (camera_width*camera_width + camera_height*camera_height)}"/>
  <xacro:property name="Iyy" value="${1.0/12.0 * camera_mass * (camera_length*camera_length + camera_height*camera_height)}"/>
  <xacro:property name="Izz" value="${1.0/12.0 * camera_mass * (camera_length*camera_length + camera_width*camera_width)}"/>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${camera_mass}"/>
      <inertia ixx="${Ixx}" ixy="0.0" ixz="0.0" iyy="${Iyy}" iyz="0.0" izz="${Izz}"/>
    </inertial>
  </link>

  <joint name="body_camera_joint" type="fixed">
    <parent link="body_link"/>
    <child link="camera_link"/>
    <origin xyz="${(body_length + camera_length)/2.0} 0 ${body_height/2.0}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link_optical"/>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <gazebo reference="camera_link">
    <material>Gazebo/Red</material>

    <sensor name="camera_sensor" type="camera">
      <topic>/camera/image_raw</topic>
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>

      <gz_frame_id>camera_rgb_frame</gz_frame_id>

      <camera name="my_camera_sensor">
        <camera_info_topic>/camera/camera_info</camera_info_topic>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>